# These are supported funding model platforms

github: ['kennedy-ex', 'riz-ex', 'aryazakaria01', 'FeriEXP', 'ParijatYT']
community_bridge: Intense-Network
custom: ['https://t.me/MarinKitagawa_IntenseBot', 'https://t.me/MarinKitagawaIntenseSupport']
